# -*- coding: utf-8 -*-
"""Regenerates game/scripts/Map/Art/SpriteData.g.cs from the concept sprite scripts (the source of truth,
docs/design/concepts/src: pp.PAL, city_sprites.ERAS, building_sprites.BUILDINGS, unit_sprites.*).
Run from anywhere:  python game/assets/map/sprites_to_cs.py
Godot ignores this file; the game only reads the generated C#."""
import os, sys

sys.dont_write_bytecode = True      # leave no __pycache__ in docs/

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..', '..'))
SRC = os.environ.get('PAX_CONCEPTS') or os.path.join(ROOT, 'docs', 'design', 'concepts', 'src')
OUT = os.path.join(ROOT, 'game', 'scripts', 'Map', 'Art', 'SpriteData.g.cs')
sys.path.insert(0, SRC)

import pp                                   # noqa: E402
from city_sprites import ERAS               # noqa: E402
from building_sprites import BUILDINGS      # noqa: E402
import unit_sprites as U                    # noqa: E402
from site_sprites import SITES, PUFF          # noqa: E402


def cs_rows(rows, indent):
    pad = ' ' * indent
    return '\n'.join('%s"%s",' % (pad, r.replace('\\', '\\\\').replace('"', '\\"')) for r in rows)


def cs_sprite_list(name, sprites, comment):
    out = ['    /// <summary>%s</summary>' % comment, '    public static readonly string[][] %s =' % name, '    {']
    for label, rows in sprites:
        out.append('        new[] { // %s' % label)
        out.append(cs_rows(rows, 12))
        out.append('        },')
    out.append('    };')
    return '\n'.join(out)


def main():
    pal = []
    for k, c in pp.PAL.items():
        a = c[3] if len(c) > 3 else 255
        pal.append("        ('%s', 0x%02X%02X%02X%02X)," % (k, c[0], c[1], c[2], a))
    units = [('SCOUT', U.SCOUT), ('CARAVAN', U.CARAVAN), ('SHIP', U.SHIP), ('NOMADS', U.NOMADS)]
    parts = [
        '// <auto-generated> by game/assets/map/sprites_to_cs.py from docs/design/concepts/src — do not edit by hand.',
        'namespace PaxPixelia.Map;',
        '',
        '/// <summary>Concept-art sprite grids (ASCII, one char per pixel, \'.\' = empty) and their master palette.',
        '/// A/N/D are the nation ramp (light/base/dark), replaced per nation when the atlas is baked.</summary>',
        'internal static class SpriteData',
        '{',
        '    /// <summary>Palette key → RGBA (0xRRGGBBAA). Keys A/N/D (nation) are filled in at bake time.</summary>',
        '    public static readonly (char Key, uint Rgba)[] Palette =',
        '    {',
        '\n'.join(pal),
        '    };',
        '',
        '    /// <summary>Keys that never get an outline (smoke, steam, glow, soft ground shadow).</summary>',
        '    public const string NoOutline = "%s";' % ''.join(sorted(pp.NO_OUTLINE)),
        '',
        cs_sprite_list('Cities', [(era, rows) for _, era, rows in ERAS], 'City per era (16×16, outline drawn inside the grid), 0 = Первобытная … 10 = Будущее.'),
        '',
        cs_sprite_list('Buildings', [(n.capitalize(), rows) for n, rows in BUILDINGS], 'Province building icons, 8×8 (+1 px outline when baked).'),
        '',
    ]
    for name, frames in units:
        parts.append(cs_sprite_list(name.capitalize(), [('frame %d' % i, f) for i, f in enumerate(frames)],
                                    '%s: 4 frames facing right (+1 px outline when baked).' % name.capitalize()))
        parts.append('')
    parts.append(cs_sprite_list('Sites', [('%s frame %d' % (name, i), f) for name, fr in SITES for i, f in enumerate(fr)],
                                'Construction scaffold per era (10×12, era-major: 4 frames each; +1 px outline when baked).'))
    parts.append('')
    parts.append(cs_sprite_list('Puff', [('frame %d' % i, f) for i, f in enumerate(PUFF)],
                                'The dust of a finished building: 2 frames, no outline (10×12).'))
    parts.append('')
    parts.append('}')
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(parts) + '\n')
    print('wrote', OUT)


if __name__ == '__main__':
    main()
