using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Godot;
using PaxPixelia.Core.Nations;
using PaxPixelia.Sim;
using PaxPixelia.World;

namespace PaxPixelia.Core;

public enum MapMode { Terrain, Political, Religion, Trade, Fertility }

/// <summary>How the UI dresses a toast: neutral info, the scout-target prompt (crosshair), or a refusal (red).</summary>
public enum ToastKind { Info, Pick, Error }

/// <summary>
/// Autoload singleton (registered in project.godot as "Game"). The hub between modules:
/// owns WorldData + GameState, the one tick clock, the command queue and typed C# events. Modules never reference
/// each other directly — they talk through Game.I (map ⇄ UI ⇄ sim ⇄ fog).
/// </summary>
public partial class Game : Node
{
    // NOTE: gameplay actions (claim, build, scouts, leaderboard…) live in Sim/GameActions.cs (partial class);
    // the setup / calendar / era contract lives in Game.Contract.cs.
    public static Game I { get; private set; }

    public const int WorldWidth = 2560, WorldHeight = 1440;

    public WorldData World { get; private set; }
    public GameState State { get; private set; }
    public bool IsReady => World != null && State != null;
    /// <summary>Seed of the world being generated (or shown).</summary>
    public int Seed { get; private set; }
    /// <summary>Wall-clock milliseconds the last NewGame took (generation + nations + fog).</summary>
    public long LastGenerationMs { get; private set; }

    public MapMode Mode { get; private set; } = MapMode.Political;
    public int Hovered { get; private set; } = -1;
    public int Selected { get; private set; } = -1;

    // ---- events (subscribe in _Ready, unsubscribe in _ExitTree) ----
    public event Action<string> GenerationProgress;     // Russian status text while generating
    public event Action WorldReady;                     // new World + State available (also after «Новый мир»)
    public event Action<int> ProvinceHovered;           // -1 = none
    public event Action<int> ProvinceSelected;          // -1 = deselect
    public event Action<MapMode> MapModeChanged;
    public event Action<IReadOnlyList<int>> ProvincesChanged; // ownership/buildings/religion changed → recolour these
    public event Action<IReadOnlyList<int>> FogChanged;       // fog state changed for these provinces (null = all)
    public event Action YearTick;                       // the calendar year changed (at most once per frame)
    public event Action MonthTick;                      // the calendar month changed (at most once per frame)
    /// <summary>A rules cycle ran (budget, growth, science…): refresh resource readouts. At most once per frame.</summary>
    public event Action CycleTick;
    public event Action<bool, int> TimeControlChanged;  // paused, speed
    public event Action<string, string> Notified;       // icon key, text
    public event Action<string, float, ToastKind> Toast; // text, seconds, kind

    public override void _EnterTree() => I = this;

    public override void _Ready() => AttachSimulation();   // Sim/GameActions.cs

    int _generation;   // a newer game (or EndGame) supersedes a generation still running
    CancellationTokenSource _genCancel;

    /// <summary>Start a game from a setup; a world pre-generated by the front-end (planet preview) is reused when given.</summary>
    public async Task NewGame(GameSetup setup, WorldData pregenerated = null)
    {
        setup ??= GameSetup.Default(Main.DefaultSeed);
        int gen = ++_generation;
        _genCancel?.Cancel();   // stop the superseded run instead of letting it finish on every core
        var cancel = _genCancel = new CancellationTokenSource();
        Setup = setup;
        World = null; State = null; Seed = setup.Seed;
        Hovered = -1; Selected = -1;
        ResetClock();
        // Progress marshals to the main thread; drop reports of a superseded run or ones arriving after WorldReady
        var progress = new Progress<string>(s => { if (gen == _generation && World == null) GenerationProgress?.Invoke(s); });
        var sw = System.Diagnostics.Stopwatch.StartNew();
        WorldData world; GameState state;
        try
        {
            var roster = NationRoster.Build(setup);
            (world, state) = await Task.Run(() =>
            {
                var w = pregenerated ?? WorldGen.Generate(setup.Seed, WorldWidth, WorldHeight, s => ((IProgress<string>)progress).Report(s), cancel.Token);
                cancel.Token.ThrowIfCancellationRequested();
                ((IProgress<string>)progress).Report("Державы и границы…");
                var st = NationGen.CreateInitialState(w, roster);
                st.Pace = Eras.ClampPace(setup.PacePermille);
                st.FogEnabled = setup.Fog;
                st.Paused = setup.StartPaused;
                Simulation.Begin(w, st);
                AttachEvents(w, st, setup);
                return (w, st);
            }, cancel.Token);
        }
        catch (OperationCanceledException) when (gen != _generation) { return; }
        catch (Exception e)
        {
            // a degenerate seed must not leave the player on the loading screen: log it and roll the next one
            GD.PushError($"world generation failed for seed {setup.Seed}: {e}");
            if (gen == _generation) await NewGame(setup with { Seed = setup.Seed + 1, SeedText = (setup.Seed + 1).ToString() });
            return;
        }
        if (gen != _generation) return;
        World = world; State = state;
        Seed = world.Seed;
        ResetClock();
        LastGenerationMs = sw.ElapsedMilliseconds;
        GD.Print($"world seed={world.Seed} provinces={world.P} nations={state.Nat.Length} ms={LastGenerationMs}");
        WorldReady?.Invoke();
        RaiseDateChanged();
    }

    /// <summary>«Новый мир»: a new world for the same setup (the player's nation and options are kept).</summary>
    public Task NewWorld(int seed) => NewGame((Setup ?? GameSetup.Default(seed)) with { Seed = seed, SeedText = seed.ToString(), StartPaused = false });

    /// <summary>Drop the running game (back to the menu). A generation still running can no longer resurrect it.</summary>
    public void EndGame()
    {
        ++_generation;
        _genCancel?.Cancel();
        World = null; State = null;
        Hovered = -1; Selected = -1;
        Mode = MapMode.Political;
        ResetClock();
        GameEnded?.Invoke();
    }

    // ---- camera bridge (MapCamera writes, UI/minimap reads & requests) ----
    public Rect2 CameraRect { get; set; }               // visible world rect; X may lie outside [0,W) (wrap)
    public int ZoomLevel { get; set; } = 3;             // MapCamera level: 0 = the ×½ atlas, 1..8
    public event Action CameraMoved;                    // raised by MapCamera when CameraRect/ZoomLevel change
    public event Action<Vector2> CameraJumpRequested;   // centre camera on a world position (minimap click, «show capital»)
    public event Action<int> ZoomRequested;             // +1 / -1 zoom step around screen centre (UI zoom buttons)
    public void RaiseCameraMoved() => CameraMoved?.Invoke();
    public void JumpCamera(Vector2 world) => CameraJumpRequested?.Invoke(world);
    public void RequestZoom(int dir) => ZoomRequested?.Invoke(dir);

    public void SetMode(MapMode m) { if (m == Mode || !Enum.IsDefined(m)) return; Mode = m; MapModeChanged?.Invoke(m); }
    public void Hover(int p) { p = ValidOrNone(p); if (p == Hovered) return; Hovered = p; ProvinceHovered?.Invoke(p); }
    public void Select(int p) { Selected = ValidOrNone(p); ProvinceSelected?.Invoke(Selected); }
    int ValidOrNone(int p) => World != null && (uint)p < (uint)World.P ? p : -1;
    public void RaiseProvincesChanged(IReadOnlyList<int> ps) => ProvincesChanged?.Invoke(ps);
    public void RaiseFogChanged(IReadOnlyList<int> ps) => FogChanged?.Invoke(ps);
    public void Notify(string icon, string text) => Notified?.Invoke(icon, text);
    public void ShowToast(string text, float seconds = 3.8f, ToastKind kind = ToastKind.Info) => Toast?.Invoke(text, seconds, kind);
    /// <summary>A refused action: red toast with the reason.</summary>
    public void ShowRefusal(string text) => ShowToast(text, 3.8f, ToastKind.Error);

    // ---- the clock: real time → ticks (Sim/Clock.cs), commands at every tick boundary ----
    /// <summary>Ticks per real second at speed 1..5 (index 0 unused).</summary>
    public static IReadOnlyList<int> TicksPerSecond => Clock.TicksPerSecond;

    readonly TickPump _pump = new();
    readonly CommandQueue _commands = new();

    /// <summary>The executed-command journal of this game (replays, desync checks, the evening summary).</summary>
    public IReadOnlyList<Cmd> Journal => _commands.Journal;

    public void SetPaused(bool p)
    {
        if (!IsReady) return;
        Issue(p ? Cmd.Pause(Viewer) : Cmd.Unpause(Viewer));
        TimeControlChanged?.Invoke(State.Paused, State.Speed);
    }

    public void SetSpeed(int s)
    {
        if (!IsReady) return;
        Issue(Cmd.SetSpeed(Viewer, Math.Clamp(s, Clock.MinSpeed, Clock.MaxSpeed)));
        TimeControlChanged?.Invoke(State.Paused, State.Speed);
    }

    /// <summary>Submit a command for the next tick boundary; single player executes it at once. Returns its result (0 = done).</summary>
    public int Issue(Cmd c)
    {
        if (!IsReady) return Commands.BadCommand;
        long day = State.Day256 / Calendar.DayUnit;
        _commands.Submit(State, c);
        int r = _commands.Flush(World, State, this);
        if (State.Day256 / Calendar.DayUnit != day) RaiseDateChanged();   // a console jump moves the calendar between ticks
        CheckEra();
        return r;
    }

    public override void _Process(double delta)
    {
        if (!IsReady) return;
        if (!State.Paused)
        {
            int n = _pump.Advance((long)(delta * TickPump.MicrosPerSecond), Clock.TicksPerSecond[State.Speed]);
            if (n > 0) RunTicks(n);
        }
        InterpolateScouts();
    }

    /// <summary>Run ticks now (the clock, fast-forward and tests) and raise the frame's events once.</summary>
    public TickReport RunTicks(int ticks)
    {
        if (!IsReady || ticks <= 0) return default;
        var r = _commands.Run(World, State, ticks, this);
        if (r.ScoutSteps > 0 || r.ScoutsFinished > 0) RaiseScoutsChanged();
        if (r.EraChanged) CheckEra();
        if (r.Cycle) CycleTick?.Invoke();
        if (r.MonthChanged) MonthTick?.Invoke();
        if (r.YearChanged) YearTick?.Invoke();
        if (r.DayChanged) RaiseDateChanged();
        return r;
    }

    /// <summary>Scouts glide between ticks: the render position leads the integer one by the fraction of the next tick.</summary>
    void InterpolateScouts()
    {
        var list = State.Scouts;
        if (list.Count == 0) return;
        float lead = State.Paused ? 0 : _pump.Fraction16 / 65536f * Scouts.SubPerTick;
        foreach (var sc in list)
            sc.Progress = Math.Min(.999f, (sc.Sub + (sc.Step < sc.Path.Length - 1 ? lead : 0)) / Scouts.SubSteps);
    }

    void ResetClock()
    {
        _pump.Reset();
        _commands.Clear();
        _dateDay = -1;
        _shownEra = State == null ? 0 : EraIndex;
    }

    int _shownEra;

    /// <summary>EraChanged fires only for the local player's own era, whoever else advanced.</summary>
    void CheckEra()
    {
        if (EraIndex == _shownEra) return;
        _shownEra = EraIndex;
        EraChanged?.Invoke(_shownEra);
    }
}
