using System;
using System.Threading.Tasks;
using PaxPixelia.World;

namespace PaxPixelia.Core;

/// <summary>
/// Wave-2 contract (STUBS, implemented by the time-foundation agent): game setup / end, the calendar API
/// (months and days instead of whole years), the current era and the per-game nation roster.
/// UI, map and front-end code against these members; keep them source-compatible.
/// </summary>
public partial class Game
{
    /// <summary>Setup of the running game (null before the first game).</summary>
    public GameSetup Setup { get; private set; }

    /// <summary>Raised after EndGame (return to the main menu).</summary>
    public event Action GameEnded;

    /// <summary>Raised when the displayed date changes (at most once per frame).</summary>
    public event Action DateChanged;

    /// <summary>Russian date text, e.g. «март 3200 до н. э.» or «12 марта 1893».</summary>
    public string DateText => State == null ? "" : Sim.GameState.YearText(State.Year);

    /// <summary>Current era of the local player (0 = Первобытная … 10 = Будущее) and its name.</summary>
    public int EraIndex => 1;
    public string EraName => "Древний мир";

    /// <summary>Nations of the running game (player's own design at [0]); use instead of the static Data.Nations.</summary>
    public Data.Nation[] Nations => Data.Nations;

    /// <summary>Start a game from a setup; a world pre-generated by the front-end (planet preview) is reused when given.</summary>
    public Task NewGame(GameSetup setup, WorldData pregenerated = null) { Setup = setup; return NewWorld(setup.Seed); }

    /// <summary>Drop the running game (back to the menu).</summary>
    public void EndGame() => GameEnded?.Invoke();

    void RaiseDateChanged() => DateChanged?.Invoke();
}
