# -*- coding: utf-8 -*-
"""Province building icons: 8x8 art (+1px automatic outline = 10x10 on the map)."""

BUILDINGS = [
 ('ФЕРМА', [
  "..tT....",
  ".tTTu...",
  "tTTTTu..",
  ".wWKd...",
  ".wWKd.E.",
  "tTtTtTtT",
  "uuuuuuuu",
  "tTtTtTtT",
 ]),
 ('ЛЕСОПИЛКА', [
  ".eE.....",
  "eEEf....",
  "Efff....",
  ".W..Twwd",
  ".W..uWWd",
  "TwwwTwwd",
  "uWWduWWd",
  "........",
 ]),
 ('КАМЕНОЛОМНЯ', [
  ".....nnn",
  "......Wn",
  "1112.W..",
  "2223W...",
  "2223W112",
  "2223.223",
  "3334.223",
  "....3334",
 ]),
 ('РЫБАЦКАЯ ПРИСТАНЬ', [
  "...W....",
  "...pp...",
  "...ppP..",
  "...pPP..",
  "wwwwwwd.",
  ".WWWWd..",
  "oOoOoOoO",
  "OoOOoOOo",
 ]),
 ('ПАСТБИЩЕ', [
  "..sss...",
  ".sssSS..",
  "KssSSS..",
  "K.d..d..",
  "........",
  "WwwWwwWw",
  "W..W..W.",
  "WwwWwwWw",
 ]),
 ('СВЯТИЛИЩЕ', [
  "...yY...",
  "..yYYr..",
  "11122223",
  ".12..23.",
  ".12rR23.",
  ".12RR23.",
  ".12..23.",
  "11222333",
 ]),
 ('РЫНОК', [
  ".ApNpNp.",
  "ApNpNpND",
  "N.N.N.D.",
  ".W....W.",
  ".WyrEyW.",
  "wwwwwwwW",
  "WWWWWWWd",
  "W.....Wd",
 ]),
 ('АМБАР', [
  "..t.....",
  ".tTu....",
  "tTTuu.t.",
  "ahhjJtTu",
  "ahhjJahj",
  "ahKjJahj",
  "ahKjJahj",
  "ahhjJahj",
 ]),
 ('ШАХТА', [
  "...23...",
  "..2334..",
  ".2Y33344",
  "2WWWWW34",
  "2WKKKW44",
  "2WKKKW34",
  "1WKKKW34",
  "n.nMn.n.",
 ]),
 ('МАНУФАКТУРА', [
  "..b.....",
  ".bbB....",
  "bbbBB...",
  "pypPPwW.",
  "pypPwdWW",
  "pKpPWWdW",
  "pKpP.WW.",
  "pKpPoOoO",
 ]),
 ('ПОРТ', [
  "...yy...",
  "...DD...",
  "...pP...",
  "...NN...",
  "..ppPP..",
  "..NNND..",
  "11122233",
  "oOoOoOoO",
 ]),
 ('УНИВЕРСИТЕТ', [
  "...AN...",
  "..ANND..",
  ".111112.",
  "11111112",
  "14141412",
  "14141412",
  "11111112",
  "22222223",
 ]),
]

for _n, _rows in BUILDINGS:
    assert len(_rows) == 8 and all(len(r) == 8 for r in _rows), (_n, [len(r) for r in _rows])

def padded(rows, p=1):
    w = len(rows[0]) + 2 * p
    return ['.' * w] * p + ['.' * p + r + '.' * p for r in rows] + ['.' * w] * p
