# -*- coding: utf-8 -*-
"""City sprites, 16x16, one per era. Keys: see pp.PAL. A/N/D = nation ramp (light/base/dark).
Outline (K) is added automatically around solid pixels; smoke/steam/glow keys are never outlined.
Light comes from the top-left: lit faces on the left/top, dark on the right/bottom."""

ERAS = [
 ('СТОЯНКА', 'Первобытная', [
  "................",
  ".....dANN.......",
  ".....dND........",
  ".....d..........",
  "...d.d..........",
  "....d...........",
  "....a...........",
  "...ahj..........",
  "...ahj.....d.d..",
  "..aahjJ.....d...",
  "..ANNND.....a...",
  ".aahhjjJ...ahj..",
  ".aahKjjJr..AND..",
  ".aaKKKjRyRaahjJ.",
  ".......dddaaKjJ.",
  "................",
 ]),
 ('ДРЕВНИЙ МИР', 'Древний мир', [
  "................",
  "......ANND......",
  "......aKKJ......",
  ".....aaJJah.....",
  ".....hhjjhJ.....",
  "....aaaJJaah....",
  "....hhhjjhhJ....",
  "...aaaaJJaaah...",
  "...hhhhjjhhhJ...",
  "..aaaaaJJaaaah..",
  "..hhhhhjjhhhhJ..",
  ".pppP.AJJA.pppP.",
  ".pKpP.NJJN.pKpP.",
  ".ppKP.NjjN.pppP.",
  ".ppKP.DJJD.pKpP.",
  "................",
 ]),
 ('АНТИЧНОСТЬ', 'Античность', [
  "................",
  ".......A........",
  ".....AANND......",
  "..AAAANNNNDDD...",
  "...111111112.e..",
  "...141414142.eE.",
  "...141414142.Ef.",
  "...141414142.Ef.",
  "..11111111112Ef.",
  ".aaaaahhhhhhjjJ.",
  ".hhhhhhhhhjjjJJ.",
  ".bbBv......bbBv.",
  ".pKpP.bbBv.pKpP.",
  ".ppKP.pKKP.pppP.",
  ".ppKP.pKKP.pKpP.",
  "................",
 ]),
 ('СРЕДНЕВЕКОВЬЕ', 'Средневековье', [
  ".......dANN.....",
  ".......dNND.....",
  "...A..2d.3..A...",
  "..AND.2234.AND..",
  ".AANDD2K34AANDD.",
  "..123.2K34.123..",
  "..123.2234.123..",
  "..1K3.2234.1K3..",
  "..123.2234.123..",
  "..123141151123..",
  "..123111112123..",
  "..12322KK33123..",
  "..1232KKKK3123..",
  "..1232KKKK3123..",
  "..1232KKKK3123..",
  "................",
 ]),
 ('ВОЗРОЖДЕНИЕ', 'Возрождение', [
  "......Y.........",
  "......p......A..",
  ".....ppP....AND.",
  "....AApND...pKP.",
  "...AANpNDD..pKP.",
  "..AANNpNNDD.pPP.",
  "..ANNNpNNND.pPP.",
  "..ppppppppP.pPP.",
  "..pKpKpKpKP.pKP.",
  ".bbbbbBBBvv.pPP.",
  ".ppppppppPP.pPP.",
  ".pppKKpppPP.pKP.",
  ".pKppKKppKP.pPP.",
  ".pKppKKppKP.pPP.",
  ".ppppKKpppP.pPP.",
  "................",
 ]),
 ('ЭПОХА ПАРА', 'Эпоха пара', [
  ".......A........",
  ".......A....zz..",
  "......ANN..zZzz.",
  "......AND...ZZ..",
  "......bBv...z...",
  "......pKP..bB...",
  ".DDD..bBv..bB...",
  "ANNND.byv.DDDDD.",
  "bbbBv.bBv.ANNND.",
  "bybyv.byv.bbbBv.",
  "bbbBv.bBv.bybBv.",
  "bybyvbbBvvbbbBv.",
  "bbbBvbyBvvbybyv.",
  "bKbBvbKKvvbbKBv.",
  "bKbBvbKKvvbbKBv.",
  "................",
 ]),
 ('ИНДУСТРИЯ', 'Индустриальная', [
  "..........xxX...",
  ".........xXXxX..",
  "..........bxX.X.",
  "..........pB....",
  "..........bB..Zx",
  "..........bB.xX.",
  "..........bB.bB.",
  "...g..g..gbB.pB.",
  "..Ag.Ag.AgbB.bB.",
  ".ANGANGANGbBnbBn",
  ".mmmmmmmmMbBMbBM",
  ".BybyBybyBbBvbBv",
  ".BBBBBBBBvbBvbBv",
  ".BKKBBKKBvbBvbBv",
  ".BKKBBKKBvbBvbBv",
  "................",
 ]),
 ('АТОМНАЯ', 'Атомная', [
  "..zzz...........",
  ".zzZzzz...ANNND.",
  "zzZZzZz...67778.",
  ".zZZzz....6q7q8.",
  "..667789..67778.",
  "...6789...6y7q8.",
  "...6789...67778.",
  "...6789...6q7y8.",
  "...6789...67778.",
  "..667789..6q7q8.",
  "..667789..67778.",
  ".66777899.6y7q8.",
  ".667K7899967788.",
  ".67KKK789967788.",
  ".67KKK78996KK88.",
  "................",
 ]),
 ('ИНФОРМАЦИЯ', 'Информационная', [
  ".......l........",
  ".......n........",
  "......AND.......",
  "......gGq.......",
  "......gyq.......",
  "......gGq.gGq...",
  "......gGy.gGQ...",
  "......gGq.gyq...",
  ".mmM..gyq.gGQ...",
  "..n...gGq.gGq.l.",
  ".6778.gGq.gGQ.n.",
  ".6yy8.gyq.gyq6n8",
  ".6778.gGqQgGQ678",
  ".6KK8.gKKQgKK6y8",
  ".6KK8.gKKQgKK678",
  "................",
 ]),
 ('КОСМОС', 'Космическая', [
  "............p...",
  "...........pPM..",
  "...........pPM..",
  ".......6...AND..",
  ".....c6i7c.pPM..",
  "......678..pqM..",
  ".......7...pPM..",
  ".......7...AND..",
  ".......7...pPM..",
  "...ggG.7...pPM..",
  "..ggGGq7..DpPMD.",
  ".gGGGqq7..DnnnD.",
  ".mmmmmMn.zZzZzZz",
  ".677K7878777788.",
  ".677K7878777788.",
  "................",
 ]),
 ('БУДУЩЕЕ', 'Будущее', [
  ".......AD.......",
  ".......67.......",
  "..........AD....",
  "....AD.6c.67....",
  "....67.67.c7....",
  "....c7.67.67....",
  "....67.6c.67....",
  "..eeEEeEEeEEEf..",
  ".66666677777888.",
  "..7788cccc8999..",
  "....99999999....",
  "................",
  "................",
  "....________....",
  ".....______.....",
  "................",
 ]),
]

for _n, _e, _rows in ERAS:
    assert len(_rows) == 16 and all(len(r) == 16 for r in _rows), (_n, [len(r) for r in _rows])
